apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-deployment
  labels:
    app: spring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
        - name: spring-demo
          image: haviineesh/spring-demo:latest
          ports:
            - containerPort: 8080
