apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
spec:
  type: NodePort
  selector:
    app: spring-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008  # Optional: sets a fixed port to access
